<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class BookingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('bookings')->truncate();

        DB::table('bookings')->insert([
            [
            'id' => 1,
            'property_id' => 1,
            'code' => 'IhrEC1',
            'host_id' => 1,
            'user_id' => 4,
            'start_date' => '2020-12-03',
            'end_date' => '2020-12-03',
            'status' => 'Pending',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 5,
            'base_price' => 5,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 0,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 5,
            'booking_type' => 'request',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => '',
            'payment_method_id' => 0,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:14:57',
            'updated_at' => '2022-12-03 00:14:57'
            ],

            [
            'id' => 3,
            'property_id' => 9,
            'code' => 'xtyc5T',
            'host_id' => 4,
            'user_id' => 3,
            'start_date' => '2020-12-03',
            'end_date' => '2020-12-03',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 150,
            'base_price' => 168,
            'cleaning_charge' => 5,
            'guest_charge' => 0,
            'service_charge' => 8,
            'security_money' => 5,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 168,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1HuB8iDpvvQP5tMRgKzxy01h',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:18:06',
            'updated_at' => '2022-12-03 00:18:06'
            ],

            [
            'id' => 4,
            'property_id' => 16,
            'code' => 'gZix6t',
            'host_id' => 3,
            'user_id' => 4,
            'start_date' => '2020-12-03',
            'end_date' => '2020-12-03',
            'status' => 'Pending',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 80,
            'base_price' => 84,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 4,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 84,
            'booking_type' => 'request',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => '',
            'payment_method_id' => 0,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:19:16',
            'updated_at' => '2022-12-03 00:19:16'
            ],

            [
            'id' => 6,
            'property_id' => 7,
            'code' => 'uef1CU',
            'host_id' => 1,
            'user_id' => 3,
            'start_date' => '2020-12-03',
            'end_date' => '2020-12-03',
            'status' => 'Accepted',
            'guest' => 2,
            'total_night' => 1,
            'per_night' => 100,
            'base_price' => 105,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 5,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 105,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1HuBBrDpvvQP5tMRGP67nSMw',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:21:22',
            'updated_at' => '2022-12-03 00:21:22'
            ],

            [
            'id' => 8,
            'property_id' => 5,
            'code' => 'JFb4Wo',
            'host_id' => 2,
            'user_id' => 4,
            'start_date' => '2020-12-05',
            'end_date' => '2020-12-07',
            'status' => 'Pending',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 20,
            'base_price' => 21,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 1,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 21,
            'booking_type' => 'request',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => '',
            'payment_method_id' => 0,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:23:05',
            'updated_at' => '2022-12-03 00:23:05'
            ],

            [
            'id' => 9,
            'property_id' => 3,
            'code' => 'gWEBQ8',
            'host_id' => 1,
            'user_id' => 4,
            'start_date' => '2020-12-04',
            'end_date' => '2020-12-04',
            'status' => 'Pending',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 7,
            'base_price' => 7,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 0,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 7,
            'booking_type' => 'request',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => '',
            'payment_method_id' => 0,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:23:48',
            'updated_at' => '2022-12-03 00:23:48'
            ],

            [
            'id' => 10,
            'property_id' => 7,
            'code' => 'cHId2J',
            'host_id' => 1,
            'user_id' => 2,
            'start_date' => '2020-12-03',
            'end_date' => '2020-12-03',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 100,
            'base_price' => 105,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 5,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 105,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1HuBG9DpvvQP5tMRChQ9vpnI',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:25:47',
            'updated_at' => '2022-12-03 00:25:47'
            ],

            [
            'id' => 11,
            'property_id' => 6,
            'code' => 'c6xF7w',
            'host_id' => 2,
            'user_id' => 1,
            'start_date' => '2020-12-01',
            'end_date' => '2020-12-01',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 120,
            'base_price' => 126,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 6,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 126,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1HuBGoDpvvQP5tMR2RndQbAx',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:26:28',
            'updated_at' => '2022-12-03 00:26:28'
            ],

            [
            'id' => 12,
            'property_id' => 10,
            'code' => '8bwLjI',
            'host_id' => 4,
            'user_id' => 1,
            'start_date' => '2020-12-07',
            'end_date' => '2020-12-08',
            'status' => 'Pending',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 244,
            'base_price' => 264,
            'cleaning_charge' => 8,
            'guest_charge' => 0,
            'service_charge' => 12,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 264,
            'booking_type' => 'request',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => '',
            'payment_method_id' => 0,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:27:20',
            'updated_at' => '2022-12-03 00:27:20'
            ],

            [
            'id' => 14,
            'property_id' => 11,
            'code' => 'E2r31u',
            'host_id' => 3,
            'user_id' => 1,
            'start_date' => '2020-12-06',
            'end_date' => '2020-12-06',
            'status' => 'Pending',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 150,
            'base_price' => 163,
            'cleaning_charge' => 5,
            'guest_charge' => 0,
            'service_charge' => 8,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 163,
            'booking_type' => 'request',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => '',
            'payment_method_id' => 0,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 00:28:08',
            'updated_at' => '2022-12-03 00:28:08'
            ],

            [
            'id' => 16,
            'property_id' => 7,
            'code' => 'eS5Ali',
            'host_id' => 1,
            'user_id' => 4,
            'start_date' => '2020-12-01',
            'end_date' => '2020-12-01',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 100,
            'base_price' => 105,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 5,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => NULL,
            'host_fee' => 0,
            'total' => 105,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1HuCTTDpvvQP5tMRITOFrAC2',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2022-12-03 01:43:37',
            'updated_at' => '2022-12-03 01:43:37'
            ],

            [
            'id' => 17,
            'property_id' => 15,
            'code' => '2VkQ7g',
            'host_id' => 3,
            'user_id' => 2,
            'start_date' => '2021-06-24',
            'end_date' => '2021-06-25',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 55,
            'base_price' => 64,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 3,
            'security_money' => 0,
            'iva_tax' => 3,
            'accomodation_tax' => 3,
            'date_with_price' => '[{\"price\":55,\"date\":\"2021-06-24\"}]',
            'host_fee' => 0,
            'total' => 64,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1J5ixIDpvvQP5tMRM46Kh3VF',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2023-06-24 10:10:17',
            'updated_at' => '2023-06-24 10:10:17'
            ],

            [
            'id' => 18,
            'property_id' => 15,
            'code' => '2BOja5',
            'host_id' => 3,
            'user_id' => 2,
            'start_date' => '2021-06-25',
            'end_date' => '2021-06-27',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 2,
            'per_night' => 55,
            'base_price' => 128,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 6,
            'security_money' => 0,
            'iva_tax' => 6,
            'accomodation_tax' => 6,
            'date_with_price' => '[{\"price\":55,\"date\":\"2021-06-25\"},{\"price\":55,\"date\":\"2021-06-26\"}]',
            'host_fee' => 0,
            'total' => 128,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1J5izADpvvQP5tMRBOTvRQED',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2023-06-24 10:12:12',
            'updated_at' => '2023-06-24 10:12:12'
            ],

            [
            'id' => 19,
            'property_id' => 15,
            'code' => 'y9zCe6',
            'host_id' => 3,
            'user_id' => 2,
            'start_date' => '2021-06-28',
            'end_date' => '2021-06-29',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 55,
            'base_price' => 64,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 3,
            'security_money' => 0,
            'iva_tax' => 3,
            'accomodation_tax' => 3,
            'date_with_price' => '[{\"price\":55,\"date\":\"2021-06-28\"}]',
            'host_fee' => 0,
            'total' => 64,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1J5j39DpvvQP5tMRZtcEu2bF',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2023-06-24 10:16:20',
            'updated_at' => '2023-06-24 10:16:20'
            ],

            [
            'id' => 20,
            'property_id' => 7,
            'code' => 'NsS5tc',
            'host_id' => 1,
            'user_id' => 2,
            'start_date' => '2021-06-28',
            'end_date' => '2021-06-30',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 2,
            'per_night' => 100,
            'base_price' => 230,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 10,
            'security_money' => 0,
            'iva_tax' => 10,
            'accomodation_tax' => 10,
            'date_with_price' => '[{\"price\":100,\"date\":\"2021-06-28\"},{\"price\":100,\"date\":\"2021-06-29\"}]',
            'host_fee' => 0,
            'total' => 230,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1J5j7KDpvvQP5tMREflBUz1r',
            'payment_method_id' => 2,
            'accepted_at' => NULL,
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2023-06-24 10:20:39',
            'updated_at' => '2023-06-24 10:20:39'
            ],

            [
            'id' => 21,
            'property_id' => 1,
            'code' => 'e3XDAn',
            'host_id' => 1,
            'user_id' => 3,
            'start_date' => '2021-06-24',
            'end_date' => '2021-06-25',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 5,
            'base_price' => 5,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 0,
            'security_money' => 0,
            'iva_tax' => 0,
            'accomodation_tax' => 0,
            'date_with_price' => '[{\"price\":5,\"date\":\"2021-06-24\"}]',
            'host_fee' => 0,
            'total' => 5,
            'booking_type' => 'request',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => 'ch_1J5kYnDpvvQP5tMRYW4SVgEU',
            'payment_method_id' => 2,
            'accepted_at' => '2021-06-24 11:51:54',
            'attachment' => NULL,
            'bank_id' => NULL,
            'note' => NULL,
            'created_at' => '2023-06-24 11:51:13',
            'updated_at' => '2023-06-24 11:53:05'
            ],

            [
            'id' => 26,
            'property_id' => 8,
            'code' => 'FGhh3y',
            'host_id' => 2,
            'user_id' => 1,
            'start_date' => '2022-02-02',
            'end_date' => '2022-02-03',
            'status' => 'Accepted',
            'guest' => 1,
            'total_night' => 1,
            'per_night' => 200,
            'base_price' => 230,
            'cleaning_charge' => 0,
            'guest_charge' => 0,
            'service_charge' => 10,
            'security_money' => 0,
            'iva_tax' => 10,
            'accomodation_tax' => 10,
            'date_with_price' => '[{\"price\":200,\"date\":\"2022-02-02\"}]',
            'host_fee' => 0,
            'total' => 230,
            'booking_type' => 'instant',
            'currency_code' => 'USD',
            'cancellation' => 'Flexible',
            'transaction_id' => ' ',
            'payment_method_id' => 4,
            'accepted_at' => NULL,
            'attachment' => 'hsbc1643692374.png',
            'bank_id' => 12,
            'note' => 'hello. paying via bank',
            'created_at' => '2023-07-01 22:43:05',
            'updated_at' => '2023-07-01 22:47:43'
            ]


        ]);
    }
}
