<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class ReviewsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reviews')->truncate();

        DB::table('reviews')->insert([

            [
            'sender_id' => 4,
            'receiver_id' => 3,
            'booking_id' => 2,
            'property_id' => 15,
            'reviewer' => 'guest',
            'message' => 'Very responsive, excellent host. Clear communication!!!!! Nice and clean. Good location. Good value. Thank you.',
            'secret_feedback' => 'A great stay in a great place! Great location, super close to the train and with a superb host who was great at communicating with me and made check-in and my stay wonderful. Will definitely be staying again when I am in the city.',
            'improve_message' => 'It was an ok stay.',
            'rating' => 5,
            'accuracy' => 5,
            'accuracy_message' => NULL,
            'location' => 5,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => 5,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => 5,
            'value' => 5,
            'value_message' => NULL,
            'house_rules' => NULL,
            'created_at' => '2020-12-03 00:52:34',
            'updated_at' => '2020-12-03 00:52:49'
            ],
                        
            [
            'sender_id' => 3,
            'receiver_id' => 4,
            'booking_id' => 2,
            'property_id' => 15,
            'reviewer' => 'host',
            'message' => 'Very great everything. Highly recommend',
            'secret_feedback' => 'great place to stay!',
            'improve_message' => NULL,
            'rating' => 5,
            'accuracy' => NULL,
            'accuracy_message' => NULL,
            'location' => NULL,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => NULL,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => NULL,
            'value' => NULL,
            'value_message' => NULL,
            'house_rules' => 5,
            'created_at' => '2020-12-03 00:52:53',
            'updated_at' => '2020-12-03 00:52:53'
            ],
                        
            [
            'sender_id' => 3,
            'receiver_id' => 4,
            'booking_id' => 3,
            'property_id' => 9,
            'reviewer' => 'guest',
            'message' => 'The stay was amazing. the staff are amazing and always helpful. the rooms are clean and the service always on time. the location is perfect walking distance from everything you ever need. a definite return stay for me.',
            'secret_feedback' => 'I Love the enviornment',
            'improve_message' => 'Transport system should be improve',
            'rating' => 5,
            'accuracy' => 5,
            'accuracy_message' => NULL,
            'location' => 5,
            'location_message' => 'Location fine',
            'communication' => 5,
            'checkin' => 5,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => 5,
            'value' => 5,
            'value_message' => 'Great value for traveller',
            'house_rules' => NULL,
            'created_at' => '2020-12-03 00:54:02',
            'updated_at' => '2020-12-03 00:54:43'
            ],
                        
            [
            'sender_id' => 4,
            'receiver_id' => 3,
            'booking_id' => 3,
            'property_id' => 9,
            'reviewer' => 'host',
            'message' => '10/10 Stay. Clean Room, clean living area, Neat little kitchen area. Davis was extremely helpful and hospitable; ensured Check in and Out was smooth, that the place was clean, and that guests were comfortable. Great communication.',
            'secret_feedback' => '10/10 Stay. Clean Room, clean living area, Neat little kitchen area. Davis was extremely helpful and hospitable; ensured Check in and Out was smooth, that the place was clean, and that guests were comfortable. Great communication.',
            'improve_message' => NULL,
            'rating' => 5,
            'accuracy' => NULL,
            'accuracy_message' => NULL,
            'location' => NULL,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => NULL,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => NULL,
            'value' => NULL,
            'value_message' => NULL,
            'house_rules' => 5,
            'created_at' => '2020-12-03 00:55:42',
            'updated_at' => '2020-12-03 00:55:42'
            ],
                        
            [
            'sender_id' => 1,
            'receiver_id' => 2,
            'booking_id' => 10,
            'property_id' => 7,
            'reviewer' => 'host',
            'message' => 'Great location & scenic views. Easy check in and check out process.',
            'secret_feedback' => 'Let us check in our bags early and were very accommodating in general.',
            'improve_message' => NULL,
            'rating' => 5,
            'accuracy' => NULL,
            'accuracy_message' => NULL,
            'location' => NULL,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => NULL,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => NULL,
            'value' => NULL,
            'value_message' => NULL,
            'house_rules' => 5,
            'created_at' => '2020-12-03 01:03:01',
            'updated_at' => '2020-12-03 01:03:01'
            ],
                        
            [
            'sender_id' => 1,
            'receiver_id' => 3,
            'booking_id' => 6,
            'property_id' => 7,
            'reviewer' => 'host',
            'message' => 'The view is to die for !',
            'secret_feedback' => 'It was an amazing stay, beautiful room and great location.',
            'improve_message' => NULL,
            'rating' => 5,
            'accuracy' => NULL,
            'accuracy_message' => NULL,
            'location' => NULL,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => NULL,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => NULL,
            'value' => NULL,
            'value_message' => NULL,
            'house_rules' => 5,
            'created_at' => '2020-12-03 01:03:36',
            'updated_at' => '2020-12-03 01:03:36'
            ],
                        
            [
            'sender_id' => 2,
            'receiver_id' => 1,
            'booking_id' => 11,
            'property_id' => 6,
            'reviewer' => 'host',
            'message' => 'It was an amazing stay, beautiful room and great location.',
            'secret_feedback' => 'Was amazing',
            'improve_message' => NULL,
            'rating' => 5,
            'accuracy' => NULL,
            'accuracy_message' => NULL,
            'location' => NULL,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => NULL,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => NULL,
            'value' => NULL,
            'value_message' => NULL,
            'house_rules' => 5,
            'created_at' => '2020-12-03 01:13:29',
            'updated_at' => '2020-12-03 01:13:29'
            ],
                        
            [
            'sender_id' => 3,
            'receiver_id' => 2,
            'booking_id' => 5,
            'property_id' => 6,
            'reviewer' => 'guest',
            'message' => 'An ok hotel first time at the hotel was much more enjoyable and I didn’t have to pay a deposit the first time so beware of the deposit fee upon arrival',
            'secret_feedback' => 'Look into parking before you book. You will have to park away from the hotel and rates are expensive.',
            'improve_message' => 'Great location and a gorgeous venue. Would definitely book again!',
            'rating' => 5,
            'accuracy' => 5,
            'accuracy_message' => 'Great location and a gorgeous venue. Would definitely book again!',
            'location' => 5,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => 5,
            'cleanliness' => 5,
            'cleanliness_message' => 'Everything great',
            'amenities' => 5,
            'value' => 5,
            'value_message' => NULL,
            'house_rules' => NULL,
            'created_at' => '2020-12-03 01:15:25',
            'updated_at' => '2020-12-03 01:15:25',
            ],
            
            [
            'sender_id' => 1,
            'receiver_id' => 2,
            'booking_id' => 11,
            'property_id' => 6,
            'reviewer' => 'guest',
            'message' => 'Nice hotel Nice people Remember Puerto Rico it’s Usa Territory.',
            'secret_feedback' => 'Super cool, would recommend and go again',
            'improve_message' => 'It was litty',
            'rating' => 5,
            'accuracy' => 5,
            'accuracy_message' => NULL,
            'location' => 5,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => 5,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => 5,
            'value' => 5,
            'value_message' => NULL,
            'house_rules' => NULL,
            'created_at' => '2020-12-03 01:18:31',
            'updated_at' => '2020-12-03 01:18:31',
            ],
            
            [
            'sender_id' => 4,
            'receiver_id' => 1,
            'booking_id' => 16,
            'property_id' => 7,
            'reviewer' => 'guest',
            'message' => 'Look into parking before you book. You will have to park away from the hotel and rates are expensive.',
            'secret_feedback' => 'The pictures made the room seem a lot larger than it actually was',
            'improve_message' => 'Everything was great',
            'rating' => 5,
            'accuracy' => 5,
            'accuracy_message' => NULL,
            'location' => 5,
            'location_message' => NULL,
            'communication' => 5,
            'checkin' => 5,
            'cleanliness' => 5,
            'cleanliness_message' => NULL,
            'amenities' => 5,
            'value' => 5,
            'value_message' => NULL,
            'house_rules' => NULL,
            'created_at' => '2020-12-03 01:45:55',
            'updated_at' => '2020-12-03 01:46:07'
            ],

        ]);
    }
}
